[package]
name = "linked-list"
version = "0.1.0"
authors = ["Alice Ryhl <alice@ryhl.io>"]

[features]
default = []
nightly = []

[dependencies]
serde = { version = "1.0", optional = true }

[dev-dependencies]
rand = "0.5"
serde_json = "1.0"
